# Generated by Django 5.0.3 on 2024-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_acessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_col', models.CharField(max_length=100)),
            ],
        ),
    ]
