# Generated by Django 5.0.3 on 2024-03-20 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_acessory_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='garage.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='garage.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='garage.color')),
            ],
        ),
    ]
